::Criteo inference head architecture evaluation
start "4096-mal:layer=1,ac_func=ReLU,use_bn=True,n-labeled=200" python model_completion.py  --num-layer 1 --activation_func_type ReLU --use-bn True --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=1,ac_func=ReLU,use_bn=False,n-labeled=200" python model_completion.py  --num-layer 1 --activation_func_type ReLU --use-bn False --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=1,ac_func=Sigmoid,use_bn=True,n-labeled=200" python model_completion.py  --num-layer 1 --activation_func_type Sigmoid --use-bn True --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=1,ac_func=Sigmoid,use_bn=False,n-labeled=200" python model_completion.py  --num-layer 1 --activation_func_type Sigmoid --use-bn False --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=2,ac_func=ReLU,use_bn=True,n-labeled=200" python model_completion.py  --num-layer 2 --activation_func_type ReLU --use-bn True --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
pause
start "4096-mal:layer=2,ac_func=ReLU,use_bn=False,n-labeled=200" python model_completion.py  --num-layer 2 --activation_func_type ReLU --use-bn False --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=2,ac_func=Sigmoid,use_bn=True,n-labeled=200" python model_completion.py  --num-layer 2 --activation_func_type Sigmoid --use-bn True --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=2,ac_func=Sigmoid,use_bn=False,n-labeled=200" python model_completion.py  --num-layer 2 --activation_func_type Sigmoid --use-bn False --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=3,ac_func=ReLU,use_bn=True,n-labeled=200" python model_completion.py  --num-layer 3 --activation_func_type ReLU --use-bn True --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=3,ac_func=ReLU,use_bn=False,n-labeled=200" python model_completion.py  --num-layer 3 --activation_func_type ReLU --use-bn False --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
pause
start "4096-mal:layer=3,ac_func=Sigmoid,use_bn=True,n-labeled=200" python model_completion.py  --num-layer 3 --activation_func_type Sigmoid --use-bn True --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=3,ac_func=Sigmoid,use_bn=False,n-labeled=200" python model_completion.py  --num-layer 3 --activation_func_type Sigmoid --use-bn False --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=4,ac_func=ReLU,use_bn=True,n-labeled=200" python model_completion.py  --num-layer 4 --activation_func_type ReLU --use-bn True --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=4,ac_func=ReLU,use_bn=False,n-labeled=200" python model_completion.py  --num-layer 4 --activation_func_type ReLU --use-bn False --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=4,ac_func=Sigmoid,use_bn=True,n-labeled=200" python model_completion.py  --num-layer 4 --activation_func_type Sigmoid --use-bn True --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
pause
start "4096-mal:layer=4,ac_func=Sigmoid,use_bn=False,n-labeled=200" python model_completion.py  --num-layer 4 --activation_func_type Sigmoid --use-bn False --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=5,ac_func=ReLU,use_bn=True,n-labeled=200" python model_completion.py  --num-layer 5 --activation_func_type ReLU --use-bn True --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=5,ac_func=ReLU,use_bn=False,n-labeled=200" python model_completion.py  --num-layer 5 --activation_func_type ReLU --use-bn False --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=5,ac_func=Sigmoid,use_bn=True,n-labeled=200" python model_completion.py  --num-layer 5 --activation_func_type Sigmoid --use-bn True --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
start "4096-mal:layer=5,ac_func=Sigmoid,use_bn=False,n-labeled=200" python model_completion.py  --num-layer 5 --activation_func_type Sigmoid --use-bn False --n-labeled 200 --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 1 --epochs 5
exit
::Yahoo Note that n-labeled represents n-labeled-per-class for this dataset.
python model_completion_mixtext.py --n-labeled 10 --resume-name Yahoo_saved_framework_lr=0.001_normal_.pth --epochs 10
python model_completion_mixtext.py --n-labeled 10 --resume-name Yahoo_saved_framework_lr=0.001_mal_.pth --epochs 10
python model_completion_mixtext.py --n-labeled 10 --resume-name Yahoo_saved_framework_lr=0.001_mal-all_.pth --epochs 10
pause
::Criteo
start "4096-normal" python model_completion.py --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --n-labeled 100 --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_normal_half=4096.pth --print-to-txt 0 --epochs 5
start "4096-mal-all" python model_completion.py --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --n-labeled 100 --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal-all_half=4096.pth --print-to-txt 0 --epochs 5
start "4096-mal" python model_completion.py --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --n-labeled 100 --party-num 2 --half 4096 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=4096.pth --print-to-txt 0 --epochs 5
pause
::CINIC10L
python model_completion.py --dataset-name CINIC10L --dataset-path D:/Datasets/CINIC10L --n-labeled 40 --party-num 2 --half 16 --k 5 --resume-name CINIC10L_saved_framework_lr=0.1_normal_half=16.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name CINIC10L --dataset-path D:/Datasets/CINIC10L --n-labeled 40 --party-num 2 --half 16 --k 5 --resume-name CINIC10L_saved_framework_lr=0.1_mal_half=16.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name CINIC10L --dataset-path D:/Datasets/CINIC10L --n-labeled 40 --party-num 2 --half 16 --k 5 --resume-name CINIC10L_saved_framework_lr=0.1_mal-all_half=16.pth --print-to-txt 1 --epochs 25
::CIFAR10
python model_completion.py --dataset-name CIFAR10 --dataset-path D:/Datasets/CIFAR10  --n-labeled 40 --party-num 2 --half 16 --k 4 --resume-name CIFAR10_saved_framework_lr=0.1_normal_half=16.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name CIFAR10 --dataset-path D:/Datasets/CIFAR10  --n-labeled 40 --party-num 2 --half 16 --k 4 --resume-name CIFAR10_saved_framework_lr=0.1_mal_half=16.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name CIFAR10 --dataset-path D:/Datasets/CIFAR10  --n-labeled 40 --party-num 2 --half 16 --k 4 --resume-name CIFAR10_saved_framework_lr=0.1_mal-all_half=16.pth --print-to-txt 1 --epochs 25
::CIFAR100
python model_completion.py --dataset-name CIFAR100 --dataset-path D:/Datasets/CIFAR100 --n-labeled 400 --party-num 2 --half 16 --k 5 --resume-name CIFAR100_saved_framework_lr=0.1_normal_half=16.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name CIFAR100 --dataset-path D:/Datasets/CIFAR100 --n-labeled 400 --party-num 2 --half 16 --k 5 --resume-name CIFAR100_saved_framework_lr=0.1_mal_half=16.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name CIFAR100 --dataset-path D:/Datasets/CIFAR100 --n-labeled 400 --party-num 2 --half 16 --k 5 --resume-name CIFAR100_saved_framework_lr=0.1_mal-all_half=16.pth --print-to-txt 1 --epochs 25
::TinyImageNet
python model_completion.py --dataset-name TinyImageNet --dataset-path D:/Datasets/TinyImageNet --n-labeled 800 --party-num 2 --half 32 --k 5 --resume-name TinyImageNet_saved_framework_lr=0.1_normal_half=32.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name TinyImageNet --dataset-path D:/Datasets/TinyImageNet --n-labeled 800 --party-num 2 --half 32 --k 5 --resume-name TinyImageNet_saved_framework_lr=0.1_mal_half=32.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name TinyImageNet --dataset-path D:/Datasets/TinyImageNet --n-labeled 800 --party-num 2 --half 32 --k 5 --resume-name TinyImageNet_saved_framework_lr=0.1_mal-all_half=32.pth --print-to-txt 1 --epochs 25
::IDC(BHI)
python model_completion.py --dataset-name BC_IDC --dataset-path D:/Datasets/BC_IDC --n-labeled 70 --party-num 2 --half 1 --k 2 --resume-name BC_IDC_saved_framework_lr=0.05_normal_party-num=2.pth --print-to-txt 1 --epochs 10 --batch-size 32
python model_completion.py --dataset-name BC_IDC --dataset-path D:/Datasets/BC_IDC --n-labeled 70 --party-num 2 --half 1 --k 2 --resume-name BC_IDC_saved_framework_lr=0.05_mal_party-num=2.pth --print-to-txt 1 --epochs 10 --batch-size 32
python model_completion.py --dataset-name BC_IDC --dataset-path D:/Datasets/BC_IDC --n-labeled 70 --party-num 2 --half 1 --k 2 --resume-name BC_IDC_saved_framework_lr=0.05_mal-all_party-num=2.pth --print-to-txt 1 --epochs 10 --batch-size 32
::BCW
--dataset-name BCW --dataset-path D:/Datasets/BreastCancerWisconsin/wisconsin.csv --n-labeled 20 --half 14 --resume-name BCW_saved_framework_lr=0.01_normal_half=14.pth