::Criteo
start "1024-normal" python model_completion.py --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --n-labeled 100 --party-num 2 --half 1024 --k 2 --resume-name Criteo_saved_framework_lr=0.05_normal_half=1024.pth --print-to-txt 1 --epochs 5
start "1024-mal" python model_completion.py --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --n-labeled 100 --party-num 2 --half 1024 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=1024.pth --print-to-txt 1 --epochs 5
start "2048-normal" python model_completion.py --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --n-labeled 100 --party-num 2 --half 2048 --k 2 --resume-name Criteo_saved_framework_lr=0.05_normal_half=2048.pth --print-to-txt 1 --epochs 5
start "2048-mal" python model_completion.py --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --n-labeled 100 --party-num 2 --half 2048 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=2048.pth --print-to-txt 1 --epochs 5
start "3072-normal" python model_completion.py --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --n-labeled 100 --party-num 2 --half 3072 --k 2 --resume-name Criteo_saved_framework_lr=0.05_normal_half=3072.pth --print-to-txt 1 --epochs 5
start "3072-mal" python model_completion.py --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --n-labeled 100 --party-num 2 --half 3072 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=3072.pth --print-to-txt 1 --epochs 5
start "5120-normal" python model_completion.py --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --n-labeled 100 --party-num 2 --half 5120 --k 2 --resume-name Criteo_saved_framework_lr=0.05_normal_half=5120.pth --print-to-txt 1 --epochs 5
start "5120-mal" python model_completion.py --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --n-labeled 100 --party-num 2 --half 5120 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=5120.pth --print-to-txt 1 --epochs 5
start "6144-normal" python model_completion.py --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --n-labeled 100 --party-num 2 --half 6144 --k 2 --resume-name Criteo_saved_framework_lr=0.05_normal_half=6144.pth --print-to-txt 1 --epochs 5
start "6144-mal" python model_completion.py --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --n-labeled 100 --party-num 2 --half 6144 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=6144.pth --print-to-txt 1 --epochs 5
start "7168-normal" python model_completion.py --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --n-labeled 100 --party-num 2 --half 7168 --k 2 --resume-name Criteo_saved_framework_lr=0.05_normal_half=7168.pth --print-to-txt 1 --epochs 5
start "7168-mal" python model_completion.py --dataset-name Criteo --dataset-path D:/Datasets/Criteo/criteo.csv --n-labeled 100 --party-num 2 --half 7168 --k 2 --resume-name Criteo_saved_framework_lr=0.05_mal_half=7168.pth --print-to-txt 1 --epochs 5
exit
::TinyImageNet
python model_completion.py --dataset-name TinyImageNet --dataset-path D:/Datasets/TinyImageNet --n-labeled 800 --party-num 2 --half 8 --k 5 --resume-name TinyImageNet_saved_framework_lr=0.1_mal_half=8.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name TinyImageNet --dataset-path D:/Datasets/TinyImageNet --n-labeled 800 --party-num 2 --half 24 --k 5 --resume-name TinyImageNet_saved_framework_lr=0.1_mal_half=24.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name TinyImageNet --dataset-path D:/Datasets/TinyImageNet --n-labeled 800 --party-num 2 --half 40 --k 5 --resume-name TinyImageNet_saved_framework_lr=0.1_mal_half=40.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name TinyImageNet --dataset-path D:/Datasets/TinyImageNet --n-labeled 800 --party-num 2 --half 48 --k 5 --resume-name TinyImageNet_saved_framework_lr=0.1_mal_half=48.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name TinyImageNet --dataset-path D:/Datasets/TinyImageNet --n-labeled 800 --party-num 2 --half 56 --k 5 --resume-name TinyImageNet_saved_framework_lr=0.1_mal_half=56.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name TinyImageNet --dataset-path D:/Datasets/TinyImageNet --n-labeled 800 --party-num 2 --half 8 --k 5 --resume-name TinyImageNet_saved_framework_lr=0.1_normal_half=8.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name TinyImageNet --dataset-path D:/Datasets/TinyImageNet --n-labeled 800 --party-num 2 --half 24 --k 5 --resume-name TinyImageNet_saved_framework_lr=0.1_normal_half=24.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name TinyImageNet --dataset-path D:/Datasets/TinyImageNet --n-labeled 800 --party-num 2 --half 40 --k 5 --resume-name TinyImageNet_saved_framework_lr=0.1_normal_half=40.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name TinyImageNet --dataset-path D:/Datasets/TinyImageNet --n-labeled 800 --party-num 2 --half 48 --k 5 --resume-name TinyImageNet_saved_framework_lr=0.1_normal_half=48.pth --print-to-txt 1 --epochs 25
python model_completion.py --dataset-name TinyImageNet --dataset-path D:/Datasets/TinyImageNet --n-labeled 800 --party-num 2 --half 56 --k 5 --resume-name TinyImageNet_saved_framework_lr=0.1_normal_half=56.pth --print-to-txt 1 --epochs 25
